require("options")
require("plugins")
require("keymaps")
require("diagnostics")
require("autocmds")

-- Plugin configuration (loaded after vim.pack.add)
require("ui")
require("lsp")
require("completion")
require("format")
require("search")
require("git")
