require("config.lazy")

require("config.base")
require("config.editor").setup()
require("config.ui")
require("config.lsp")
require("config.format")
require("config.autocomplete")
require("config.search")
require("config.git")
